import { createClient } from "@/lib/supabase/server";
import { createClient as createAdminClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { type NextRequest } from "next/server";

export async function GET(request: NextRequest) {
  const requestUrl = new URL(request.url);
  const code = requestUrl.searchParams.get("code");
  const next = requestUrl.searchParams.get("next") || "/dashboard";
  const type = requestUrl.searchParams.get("type"); // Can be "email_change", "signup", or "recovery"

  if (code) {
    const supabase = await createClient();
    
    // Exchange the code for a session
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    
    if (!error) {
      // Get the user to check if email is verified
      const { data: { user } } = await supabase.auth.getUser();
      
      if (user?.email_confirmed_at) {
        // Email is verified - redirect immediately
        // Profile check/creation happens in background (non-blocking)
        // Database trigger should handle profile creation, but if it doesn't,
        // we'll create it asynchronously without blocking the redirect
        
        // Start profile check/creation in background (don't await)
        if (user.email) {
          (async () => {
            try {
              // Quick check if profile exists
              const { data: existingProfile, error: profileError } = await supabase
                .from("user_profiles")
                .select("id")
                .eq("id", user.id)
                .single();

              if (!existingProfile && user.email) {
                // Profile doesn't exist - create it using service role to bypass RLS
                console.log("⚠️ User profile not found, creating it via service role (background)...");
                
                const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
                const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

                if (supabaseUrl && supabaseServiceKey) {
                  const adminClient = createAdminClient(supabaseUrl, supabaseServiceKey, {
                    auth: {
                      autoRefreshToken: false,
                      persistSession: false,
                    },
                  });

                  // Generate email hash and license ID using RPC functions
                  const { data: emailHash } = await adminClient.rpc("generate_email_hash", {
                    email_address: user.email,
                  });

                  const { data: licenseId } = await adminClient.rpc("generate_unique_license_id");

                  // Insert profile with all required fields
                  const { data: newProfile, error: insertError } = await adminClient
                    .from("user_profiles")
                    .insert({
                      id: user.id,
                      email: user.email,
                      email_hash: emailHash,
                      license_id: licenseId,
                      role: "user",
                      subscription_tier: "free",
                      subscription_status: "trial",
                      subscription_start_date: new Date().toISOString(),
                      subscription_end_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(), // 14 days from now
                    })
                    .select()
                    .single();

                  if (insertError) {
                    console.error("Failed to create user profile:", insertError);
                    // Try fallback insert without email_hash and license_id (they might be generated by trigger)
                    const { error: fallbackError } = await adminClient
                      .from("user_profiles")
                      .insert({
                        id: user.id,
                        email: user.email,
                        role: "user",
                        subscription_tier: "free",
                        subscription_status: "trial",
                        subscription_start_date: new Date().toISOString(),
                        subscription_end_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
                      })
                      .select()
                      .single();

                    if (fallbackError) {
                      console.error("Fallback profile creation also failed:", fallbackError);
                    } else {
                      console.log("✅ User profile created successfully (fallback method)");
                    }
                  } else {
                    console.log("✅ User profile created successfully");
                  }
                } else {
                  console.error("⚠️ Service role key not available - cannot create profile fallback");
                }
              } else if (existingProfile) {
                console.log("✅ User profile already exists");
              }
            } catch (profileCheckError: any) {
              console.error("Error checking/creating user profile (background):", profileCheckError);
              // Continue anyway - user can still access the app
            }
          })();
        }

        // Check if this is a password recovery flow
        if (type === "recovery") {
          // Redirect to password reset page
          const resetUrl = new URL("/reset-password", requestUrl.origin);
          return NextResponse.redirect(resetUrl);
        }
        
        // Email is verified, redirect immediately without waiting for profile check
        // Add verified=true parameter to trigger auto-refresh and login
        const redirectUrl = new URL(next, requestUrl.origin);
        redirectUrl.searchParams.set("verified", "true");
        
        // Check if this is an email change verification
        // Supabase includes type=email_change in the URL for email change verifications
        if (type === "email_change" || type === "email") {
          redirectUrl.searchParams.set("email_updated", "true");
        }
        
        // Redirect immediately - profile creation happens in background
        return NextResponse.redirect(redirectUrl);
      } else {
        // Email not verified yet, redirect to home with message
        const redirectUrl = new URL("/?verified=false", requestUrl.origin);
        return NextResponse.redirect(redirectUrl);
      }
    } else {
      // Error exchanging code, redirect to home with error
      console.error("Error exchanging code for session:", error);
      const redirectUrl = new URL("/?error=auth_failed", requestUrl.origin);
      return NextResponse.redirect(redirectUrl);
    }
  }

  // No code provided, redirect to home
  return NextResponse.redirect(new URL("/", requestUrl.origin));
}

